In [2]:
import torch
import torch.nn as nn
import numpy as np

In [3]:
class Linear(nn.Module):
    def __init__(self, input_size, output_size):
        super(Linear, self).__init__()
        self.fc1 = nn.Linear(input_size, output_size) 

    def forward(self, x):
        out = self.fc1(x)
        return out

In [4]:
model = Linear(2, 1)
x = torch.from_numpy(np.array([1.,2.], dtype=np.float32))
y = model.forward(x)

print y

print ('w: ', model.fc1.weight)
print ('b: ', model.fc1.bias)
print ('w shape: ', model.fc1.weight.shape)

print ('grad w: ', model.fc1.weight.grad)
print ('grad b: ', model.fc1.bias.grad)

tensor([ 1.3197])
('w: ', Parameter containing:
tensor([[ 0.2421,  0.6833]]))
('b: ', Parameter containing:
tensor([-0.2890]))
('w shape: ', torch.Size([1, 2]))
('grad w: ', None)
('grad b: ', None)


In [5]:
y.backward()


print ('w: ', model.fc1.weight)
print ('b: ', model.fc1.bias)

print ('grad w: ', model.fc1.weight.grad)
print ('grad b: ', model.fc1.bias.grad)

('w: ', Parameter containing:
tensor([[ 0.2421,  0.6833]]))
('b: ', Parameter containing:
tensor([-0.2890]))
('grad w: ', tensor([[ 1.,  2.]]))
('grad b: ', tensor([ 1.]))


In [9]:
x = torch.randn(10, 3)
y = torch.randn(10, 2)
model = Linear(3, 2)
# Build loss function and optimizer.
loss_function = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)
# Forward pass.
for i in range(10):
    # equal to model.forward(x)
    pred = model(x)
    # Compute loss.
    loss = loss_function(pred, y)
    print('loss after ',i,' step optimization: ', loss.item())
    
    
    optimizer.zero_grad()
    # Backward pass.
    loss.backward()
    # 1-step gradient descent.
    optimizer.step()
    # Print out the loss after 1-step gradient descent.



('loss after ', 0, ' step optimization: ', 1.3124338388442993)
('loss after ', 1, ' step optimization: ', 1.1281542778015137)
('loss after ', 2, ' step optimization: ', 1.0124635696411133)
('loss after ', 3, ' step optimization: ', 0.9383653402328491)
('loss after ', 4, ' step optimization: ', 0.8896365165710449)
('loss after ', 5, ' step optimization: ', 0.8565107583999634)
('loss after ', 6, ' step optimization: ', 0.8330961465835571)
('loss after ', 7, ' step optimization: ', 0.8158258199691772)
('loss after ', 8, ' step optimization: ', 0.8025298118591309)
('loss after ', 9, ' step optimization: ', 0.7918784618377686)
