In [7]:
import torch
import numpy as np

In [8]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [9]:
tensor_a = torch.from_numpy(a)
print(tensor_a)

tensor([ 1,  2,  3])


In [10]:
numpy_a = tensor_a.numpy()
print(numpy_a)

[1 2 3]
